ssh_servers:
  vars:
    sudo_flags: "-HE"
    ansible_port: "22"
    ansible_user: "root"
    ansible_ssh_common_args: "-i {{cops_deploy_ssh_key_paths['staging'].path}}"
portus_servers:
  hosts:
    staging-myapop.foo.net
app_servers:
  children:
    portus_servers
controller:
  localhost:
    ansible_connection: local
